### ISSUE TITLE
can't change clarinet.MAX_BUFFER_LENGTH

### ISSUE THREAD

**Issue by kapouer** [fent/node-jstream#3]
Hi,
i'm parsing a stream of objects containing sometimes long data-uri,
and i'd need to set
```
clarinet.MAX_BUFFER_LENGTH = 1024 * 1024;
```
but jstream doesn't expose clarinet.
It would nice JStream took options that allow that kind of change.

**Comment by fent** [comment]
Hi

Doing `var clarinet = require('jstream/node_modules/clarinet');` would work. But let me know if including the dependency in the jstream constructor would make more sense.

**Comment by kapouer** [comment]
It works as a quick workaround, but this is bad practice:

- they day you update jstream to another json parsing module (for the sake of the argument) the workaround breaks.
- Also i'm pretty sure npm 3 will install `clarinet` in my project's node_modules, not in jstream/node_modules, so because that kind of workaround assumes how modules are organized, it is going to fail miserably.

**Comment by kapouer** [comment]
Also the MAX_BUFFER_LENGTH seems to be the only option that's worth changing.
Maybe jstream should allow changing that value without giving user access to underlying clarinet.

**Comment by fent** [comment]
If it's the only option worth changing, then a direct access to it might be best.

And can't accept it as part of options to JStream instances since it's a global.

**Comment by kapouer** [comment]
Thank you !
